biblioteka/urls.py
from django.contrib import admin
from django.urls import path, include


from wyporzyczalnia import views as w_views
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.conf import settings

from wyporzyczalnia.views import all_books

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', w_views.index, name='index'),
    path('contact/', w_views.contact, name='contact'),
    path('wyporzyczalnia/', include('wyporzyczalnia.urls')),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', w_views.register, name='register'),
    path('booklist/', w_views.BookListView.as_view(), name="all_books"),
    path('accounts/', include('django.contrib.auth.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wyporzyczalnia/urls.py
from django.urls import path
from . import views
from .views import all_books

urlpatterns = [
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed')
    # path('wszystkie/', wszystkie_filmy, name='wszystkie_filmy'),
    # path('nowy/', nowy_film, name='nowy_film'),
    # path('edytuj/<int:id>', edytuj_film, name='edytuj_film'),
    # path('usun/<int:id>', usun_film, name='usun_film')
]

wyporzyczalnia/models.py
import uuid

from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date

# Create your models here.
class Book(models.Model):
    title = models.CharField(max_length=64, blank=False, unique=True)
    author = models.ForeignKey('Author', max_length=32, blank=False, null=True, on_delete=models.SET_NULL)
    year = models.PositiveSmallIntegerField(default=2000)
    description = models.TextField(default="")
    release = models.DateField(null=True, blank=True)
    rate = models.DecimalField(max_digits=4, decimal_places=2, null=True, blank=True)
    image = models.ImageField(upload_to="okładki", null=True, blank=True)
    isbn = models.CharField('ISBN', max_length=13, unique=True, null=True)
    bookgenre = models.ManyToManyField('BookGenre')

    def __str__(self):
        return self.title_with_author()

    def title_with_author(self):
        return f"{self.title} ({self.author})"

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):
        return ', '.join(genre.name for genre in self.bookgenre.all()[:3])

    display_genre.short_description = 'Genre'
    def display_author(self):
        return f"{self.author.first_name} {self.author.last_name}"



class BookGenre(models.Model):
    name = models.CharField(max_length=100, help_text="Podaj typ książki (drama, horror etc)")

    def __str__(self):
        return self.name


class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    due_back = models.DateField(null=True, blank=True)
    book = models.ForeignKey('Book', on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=100)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    ACTUAL_STATUS = (
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
        ('u', 'Unknown'),
    )
    status = models.CharField(max_length=1, choices=ACTUAL_STATUS, default='u', blank=True, help_text='Book status')

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    class Meta:
        permissions = (("can_mark_returned", "Set book as returned"),)
        ordering = ['due_back']

    def __str__(self):
        return f"{self.id} ({self.book.title})"


class Author(models.Model):
    first_name = models.CharField(max_length=32)
    last_name = models.CharField(max_length=32)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        return reverse('author_detail', args=[str(self.id)])


    def __str__(self):
        return f"{self.last_name} {self.first_name}"

wyporzyczalnia/forms.py
from django.forms import ModelForm
from .models import Book
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'author', 'description', 'year', 'release', 'image', 'rate']


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

wyporzyczalnia/views.py
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.shortcuts import render, redirect
from django.views import generic

from .forms import UserRegisterForm
from .models import Book, Author, BookInstance, BookGenre
from django.contrib.auth.mixins import LoginRequiredMixin


def contact(request):
    return render(request, 'contact.html', {})


def index(request):
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()
    num_authors = Author.objects.count()
    type_genres = BookGenre.objects.all()
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1
    context = {
        'type_genres': type_genres,
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_visits': num_visits,
    }
    return render(request, 'index.html', context=context)


def login(request):
    return render(request)


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}!')
            form.save()
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'register.html', {'form': form})


def all_books(request):
    books = Book.objects.all()
    author = Author.objects.all()
    return render(request, 'listofbooks.html', {'books': books, 'author': author})


class BookListView(generic.ListView):
    model = Book
    context_object_name = 'my_book_list'  # your own name for the list as a template variable
    queryset = Book.objects.filter(title__icontains='war')[:5]  # Get 5 books containing the title war
    template_name = 'listofbooks.html'  # Specify your own template name/location

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        context = super(BookListView, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        context['some_data'] = 'This is just some data'
        return context

    def get_queryset(self):
        return Book.objects.all()


class AuthorListView(generic.ListView):
    model = Book
    context_object_name = 'my_author_list'  # your own name for the list as a template variable
    queryset = Author.objects.filter(first_name__icontains='war')[:5]  # Get 5 books containing the title war
    template_name = 'listofAuthors.html'  # Specify your own template name/location

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        context = super(AuthorListView, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        context['some_data'] = 'This is just some data'
        return context

    def get_queryset(self):
        return Author.objects.all()


class BookDetailView(generic.DetailView):
    model = Book

    def book_detail_view(request, primary_key):
        book = get_object_or_404(Book, pk=primary_key)
        return render(request, 'book_detail.html', context={'book': book})


class AuthorDetailView(generic.DetailView):
    model = Author

    def author_detail_view(request, primary_key):
        author = get_object_or_404(Author, pk=primary_key)
        return render(request, 'author_detail.html', context={'author': author})


class LoanedBooksByUserListView(LoginRequiredMixin,generic.ListView):
    """Generic class-based view listing books on loan to current user."""
    model = BookInstance
    template_name ='bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')

wyporzyczalnia/templates/bookinstance_list_borrowed_user.html
{% extends 'glowny.html' %}

{% block strona %}
<div class="card-body bg-dark text-white "style="width: 90%; margin: 10px; >
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}
</div>
{% endblock %}

wyporzyczalnia/templates/contact.html
{% extends 'glowny.html' %}
{% load static %}
{% block tytul %} Strona kontaktowa {% endblock %}
{% block strona %} phone number 0700880774 {% endblock %}

wyporzyczalnia/templates/glowny.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <script src="https://kit.fontawesome.com/bb5c50a176.js" crossorigin="anonymous"></script>
     <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
    <title>{% block tytul %} {% endblock %}</title>
</head>
<body class="p-3 mb-2 bg-secondary text-white" style="background-image: url('https://zpopk.pl/wp-content/uploads/2015/05/trinity-college-old-library.jpg')">
<div style="padding:10px">
  <div class="b-example-divider"></div>
  <header class="p-3 bg-dark text-white">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="{% url 'index' %}" class="nav-link px-2 text-secondary">Home</a></li>
<!--          <li><a href="#" class="nav-link px-2 text-white">Search</a></li>-->
          <li><a href="{% url 'all_books' %}" class="nav-link px-2 text-white">List of Books</a></li>
            {% if user.is_authenticated %}
          <li><a href="{% url 'my-borrowed' %}"  class="nav-link px-2 text-white">My Borrowed</a></li>
            {% endif %}
            <li><a href="{% url 'contact' %}" class="nav-link px-2 text-white">Contact</a></li>
        </ul>
        <div class="text-end">
            {% if user.is_authenticated %}
        <a class='btn btn-secondary'>Witaj {{ user.username }}</a>
        <a href="{% url 'logout' %} " class='btn btn-secondary'>Logout </a>
        {% else %}

        <a href="{% url 'login' %}" class="btn btn-success">Login </a>
        <a href="{% url 'register' %}" class="btn btn-success">Register </a>
        {% endif %}

        </div>
      </div>
    </div>
  </header>
</div>
    {% block sidebar %}<!-- insert default navigation text for every page -->{% endblock %}
    {% block strona %} {% endblock %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} " style="width: 22rem;">{{ message }}</div>
        {% endfor %}
    {% endif %}
</body>
</html>

wyporzyczalnia/templates/index.html
{% extends 'glowny.html' %}
{% load static %}
{% block tytul %} Strona Główna biblioteki {% endblock %}
<div class="col-sm-10 ">{% block strona %}
  <div class="card bg-dark" style="width: 36rem; margin:10px">
  <div class="card-body bg-dark">
    <h3>Dane o wyposarzeniu Biblioteki</h3>
  <h5>Biblioteka posiada następujące zasoby:</h5>

    <li><strong>Books:</strong> {{ num_books }}</li>
    <li><strong>Copies:</strong> {{ num_instances }}</li>
    <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
    <div class="col-sm-10 ">
  <div class="card bg-dark" style="width: 18rem; ">
    {% for genre in type_genres %}
      <li><strong>Genres:</strong> {{ genre.name }}</li>
    {% endfor  %}
        </div>
    </div>

    <p>You have visited this page {{ num_visits }} time{{ num_visits|pluralize }}.</p>

{% endblock %}

    </div>
    </div>
</div>

wyporzyczalnia/templates/listofbooks.html
{% extends 'glowny.html' %}
{% load static %}
{% block tytul %} Lista Książek{% endblock %}
 {% block strona %}

{% if my_book_list|length == 0 %}
<h2>Brak książek w bazie</h2>
{% else %}
<div class="card-body bg-dark text-white "style="width: 90%; margin: 5%">
    {% for book in my_book_list %}



                  <div class="row">
                    <div class="col-3">
                        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> {{ book.author }}
                        <img src="/media/{{ book.image }}" class="film-plakat" style="width:75%;">
                   </div>
                      <div class="col-9">
                       <p class="card-text">{{book.description}}</p>
                   </div>
                   </div>

                     <hr>

        {% endfor %}
    {% endif %}
  </div>

{% endblock %}

wyporzyczalnia/templates/register.html
{% extends 'glowny.html' %}
{% load crispy_forms_tags %}
{% block tytul %} Rejestracja {% endblock %}
{% block strona %}
    <div class="content-section card bg-dark" style="width: 30rem; margin:10px;">
        <div class="card p-3 mb-2 bg-dark text-white" style="padding: 20px;">
        <form method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                {{form|crispy}}

            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit" style="padding:10px;">Sign up</button>
            </div>
        </form>
        <div class="">
            <small class="text-muted">Alredy Have An account?
                <a href="{% url 'login' %}" class="btn btn-secondary btn-lg">Zaloguj</a>
            </small>

        </div>


        </div>
    </div>

{% endblock %}

wyporzyczalnia/templates/wyporzyczalnia/author_detail.html
{% extends "glowny.html" %}

{% block strona %}
<div class="card-body bg-dark text-white "style="width: 90%; margin: 5%">
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> <a href="{{ book.author.get_absolute_url  }}">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ book.description }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>Genre:</strong> {{ book.bookgenre.all|join:", " }}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
      <hr>
      <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
      </p>
      {% if copy.status != 'a' %}
        <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
      {% endif %}
      <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
      <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
    {% endfor %}
  </div>
</div>
{% endblock %}

wyporzyczalnia/templates/wyporzyczalnia/book_detail.html
{% extends "glowny.html" %}

{% block strona %}
<div class="card-body bg-dark text-white "style="width: 90%; margin: 5%">
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> {{ book.author }}</p> <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ book.description }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>Genre:</strong> {{ book.bookgenre.all|join:", " }}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
      <hr>
      <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
      </p>
      {% if copy.status != 'a' %}
        <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
      {% endif %}
      <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
      <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
    {% endfor %}
  </div>
</div>
{% endblock %}